name: time_span
description: a dart library that calculates the time span in hours or minutes for two given time strings of format HH:MM.
version: 1.0.3

homepage: https://github.com/AndreeWille/time-span
repository: https://github.com/AndreeWille/time-span
issue_tracker: https://github.com/AndreeWille/time-span/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  time_parser: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
