name: time_span
description: A starting point for Dart libraries or applications.
version: 1.0.1

homepage: https://github.com/AndreeWille/time_span
repository: https://github.com/AndreeWille/time_span
issue_tracker: https://github.com/AndreeWille/time_span/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  time_parser: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
